name: flutter_form_registry
description: A workaround to track some FormFields in the tree. Support checking `FormField` is fully visible and scrolling into the view.
version: 0.7.0
repository: https://github.com/thanhle1547/flutter_form_registry

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
